# Generated by Django 5.2 on 2025-04-17 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان(به فارسی)')),
                ('url_name', models.CharField(max_length=300, verbose_name='عنوان در url(به انگلیسی)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده/حذف نشده')),
                ('title_english', models.CharField(max_length=200, verbose_name='نام برند(به انگلیسی)')),
            ],
            options={
                'verbose_name': 'برندها',
                'verbose_name_plural': 'برند',
            },
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان(به فارسی)')),
                ('url_name', models.CharField(max_length=300, verbose_name='عنوان در url(به انگلیسی)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده/حذف نشده')),
                ('title_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='دسته بنده')),
            ],
            options={
                'verbose_name': 'دسته بنده ها',
                'verbose_name_plural': 'دسته بندی',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='عنوان')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت')),
                ('short_body', models.CharField(db_index=True, max_length=300, verbose_name='توضیحات کوتاه')),
                ('body', models.TextField(db_index=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده/حذف نشده')),
                ('is_sale', models.BooleanField(default=False, null=True, verbose_name='محصول تخفیف دارد./ندارد')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='درصد تخفیف')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, default='', max_length=200, unique=True, verbose_name='عنوان در url')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brands', verbose_name='برند')),
                ('category_product', models.ManyToManyField(db_index=True, to='products.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول ',
                'verbose_name_plural': 'محصولات ',
            },
        ),
        migrations.CreateModel(
            name='product_galry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/galry')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف شده/حذف نشده')),
                ('product_gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='گالری')),
            ],
        ),
    ]
